### PR TITLE
8 6 checkout function

### PR DESCRIPTION
**Pull request by argaukel**
moved logic for "request" item to app.js to be accessed by rest of app - clicking request populates "cart" array in state on app.js

### CODE REVIEW

**Comment by jlouie10** [comment]
@argaukel what do you think of creating this as it's own component that other components can `import`? For example, it would act like a middleware if a page needs it:

```
<App>
  <MyComponent>
    <Request />
    <OtherStuff />
  </MyComponent>
</App>
```

Otherwise, wouldn't it run for every page, regardless if the page requires the feature? 

Or, would you say that all pages need it?

**Comment by argaukel** [comment]
I moved it here so that it could be available to be passed into the user-cart, rather than having it in the user-checkout where it's a child of the app/parent, if that makes sense. I was thinking we may need the cart data back on the app level to get passed into the admin side.

that being said, if there's a better/preferred way to handle this I'm happy to made adjustments!

**Comment by jlouie10** [comment]
I think this is ultimately fine. But I would recommend thinking about componentizing inventory and checkout. 

--You can stop reading here if you want--

A recurring theme of Paul's has been "modular design." The idea being that each component or module has as little interdependence as possible. Two of the benefits are:

  1) scalability - features can be developed:
    * quickly (a team of engineers can work on developing multiple features at once and save time by reusing modules)
    * in bite sized chunks (the code is easy to read, easy to understand)
  2) reliability - if one module crashes, others do not

With including the update in App.js, the db fetch is not opt in, so it will always run, no matter what. I think @ebadowski also made reference to this about having a lot of stuff to load as soon as the app is started.

The other thing is about checkout. So, that's really good thinking about the "cart," having it persist no matter which page the user is on. However, another way of implementing it is to save it to the database (we never talked about this in the past). Sort of like how it would be on Amazon, even if the user reloads the page or accesses the app from another session, the shopping cart would still be saved, as opposed to storing it in `state.`

**Comment by argaukel** [comment]
thanks for your thoughts! I'll talk this over with Paul get his feedback. 

storing the cart in the database sounds really interesting! We can decide today how we want to move forward with it before I dig in much deeper.

**Pull request closed without merging**
