### PR TITLE
Client mvc intitialisation

### PR DESCRIPTION
**Pull request by ebadowski**
Also created admin-inventory template

### CODE REVIEW

**Comment by jlouie10** [comment]
@ebadowski how did you plan on using Express and Mongoose in the React app? I noticed they were in the React app package.json.

**Comment by ebadowski** [comment]
Ah no; was just a copy paste, we shouldn’t need them on the client end

**Comment by ebadowski** [comment]
>@ebadowski how did you plan on using Express and Mongoose in the React app? I noticed they were in the React app package.json.

@jlouie10 Ah no; was just a copy paste, we shouldn’t need them on the client end

**Comment by jlouie10** [comment]
I removed Express and Mongoose, so if we're cool with that we should approve and merge.

**Comment by ebadowski** [comment]
>I removed Express and Mongoose, so if we're cool with that we should approve and merge.

@jlouie10 looks good, I just can’t merge the branch myself

**Pull request merged**
